### ISSUE TITLE
Control email of github-actions bot?

### ISSUE THREAD

**Issue by mgeisler** [parkerbxyz/suggest-changes#41]
Hello! I found this GH action recently and I would love to use it in my repository: https://github.com/google/comprehensive-rust/pull/2396.

However, I've run into a small problem: we use a CLA bot to ensure that we have the correct paperwork for everybody who contributes to the repository. It seems we don't have this for the github-actions user which becomes a co-author of the PR:

![image](https://github.com/user-attachments/assets/13c1f9da-ee68-4f6c-96b4-236e5e323fdd)

I will try to talk with the people in Google who maintain the CLA bot about this — I just wanted to note the issue and ask if you perhaps know of a way to control the email address used? Perhaps it would be possible to post the comment as a different user completely?

Ah, reading a bit more lead me to [this discussion](https://github.com/orgs/community/discussions/26560#discussioncomment-3252340) — the email address used it the same for all actions done by the bot. So I guess this would have to be handled on our side.

**Comment by mgeisler** [comment]
https://github.com/actions/stale/issues/61#issuecomment-625653899 seems to answer my first question — it would be possible to use a different bot user by changing the token used.

**Comment by parkerbxyz** [comment]
> https://github.com/actions/stale/issues/61#issuecomment-625653899 seems to answer my first question — it would be possible to use a different bot user by changing the token used.

Yes, that's right. The default token used is [`GITHUB_TOKEN`](https://docs.github.com/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret). You can use a different token with the `token` input. I recommend using a [GitHub App token](https://docs.github.com/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow) in this case. Here's an example:

```yml
jobs:
  suggest-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Suggest changes
        uses: parkerbxyz/suggest-changes@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
```

Let me know if that answers your questions and if you have any additional questions. 🙂
